# Generated by Django 5.0.2 on 2024-04-27 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_cities_countries_departments_identifications_types_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='students',
            name='id_person',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 514287)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 514287)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 534298)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 534298)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 534298)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 534298)),
        ),
        migrations.AlterField(
            model_name='identifications_types',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 534298)),
        ),
        migrations.AlterField(
            model_name='identifications_types',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 30, 53, 534298)),
        ),
        migrations.AlterField(
            model_name='students',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
