# Generated by Django 5.0.2 on 2024-04-27 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_delete_person_delete_user_students_id_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 707830)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 707830)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 727698)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 727698)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 726698)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 726698)),
        ),
        migrations.AlterField(
            model_name='identifications_types',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 727698)),
        ),
        migrations.AlterField(
            model_name='identifications_types',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 19, 32, 18, 727698)),
        ),
    ]
